import React from 'react';
import {View, Text, TouchableOpacity, StyleSheet} from 'react-native';
import {RFPercentage} from 'react-native-responsive-fontsize';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {Fonts} from '@constants/Fonts';
import {Colors} from '@constants/themeColors';
import {MoreVertical} from 'lucide-react-native';
import moment from 'moment';
import CustomButton from '@components/Buttons/customButton';
import {capitalize} from '@utils/Helpers';
import StatusBox from './StatusBox';
import { statusStyles } from '@constants/DummyData';
import { useTranslation } from 'react-i18next';
import logger from '@utils/logger';

const AutomatedDocumentsCard = ({item, onSendDocument, isLoading, type}) => {
  const isDocumentHistory = type === 'documentHistory';
  const {t} = useTranslation();




  const style = statusStyles[capitalize(item?.status)]
  return (
    <View style={styles.card}>
      {/* Header Row */}
      <View style={styles.headerRow}>
        <Text style={styles.idText}>#{item.id}</Text>
        <Text style={styles.dateText}>
          {isDocumentHistory
            ? moment(item.created_at).format('DD MMM, YYYY')
            : moment(item.current_date).format('DD MMM, YYYY')}
        </Text>
      </View>

      {/* Divider */}
      <View style={styles.divider} />

      {/* Info Rows */}
      <View style={styles.infoRow}>
        <Text style={styles.label}>{t('Name')}:</Text>
        <Text style={styles.value}>
          {isDocumentHistory ? item.worker_name : item.name ? item.name : 'N/A'}
        </Text>
      </View>

      <View style={styles.infoRow}>
        <Text style={styles.label}>
          {t(isDocumentHistory ? 'Generated By' : 'Department')}:
        </Text>
        <Text style={styles.value}>
          {isDocumentHistory
            ? capitalize(item.generated_by_name)
            : item.department
            ? item.department
            : 'N/A'}
        </Text>
      </View>

      <View style={styles.infoRow}>
        <Text style={styles.label}>
          {t(isDocumentHistory ? 'Type' : 'Work Schedule')}:
        </Text>
        <Text style={styles.value}>
          {isDocumentHistory
            ? item.document_type === 'employment_certificate'
              ? 'Employment Certificate'
              : 'Pay Slip'
            : item.work_schedule
            ? item.work_schedule
            : 'N/A'}
        </Text>
      </View>

      <View style={styles.infoRow}>
        <Text style={styles.label}>
          {t(isDocumentHistory ? 'Period' : 'Phone Number')}:
        </Text>
        <Text style={styles.value}>
          {isDocumentHistory
            ? item.period
              ? item.period
              : 'N/A'
            : item.worker_mobile
            ? item.worker_mobile
            : 'N/A'}{' '}
          {}
        </Text>
      </View>

      {isDocumentHistory ? (
        <View style={styles.infoRow}>
          <Text style={styles.label}>{t("Status")}:</Text>
          <StatusBox
            backgroundColor={style?.backgroundColor}
            color={style?.color}
            status={capitalize(item.status)}
            icon={style?.icon}
          />
        </View>
      ) : (
        <View style={styles.infoRow}>
          <Text style={styles.label}>{t("Email")}:</Text>
          <Text style={[styles.value, {width: '50%'}]}>
            {item.worker_email ? item.worker_email : 'N/A'}
          </Text>
        </View>
      )}

{
  !isDocumentHistory  && <CustomButton
  text={'View Document'}
  containerStyle={styles.actionRow}
  onPress={() => onSendDocument(item)}
  textStyle={styles.actionText}
  isLoading={isLoading}
/>
}
      
    </View>
  );
};

export default AutomatedDocumentsCard;

const styles = StyleSheet.create({
  card: {
    backgroundColor: Colors.lightTheme.secondryColor,
    borderRadius: wp(3),
    marginVertical: hp(1),
    padding: wp(4),
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: hp(0.5),
  },
  idText: {
    fontFamily: Fonts.PoppinsSemiBold,
    fontSize: RFPercentage(2),
    color: Colors.lightTheme.primaryColor,
  },
  dateText: {
    fontFamily: Fonts.PoppinsRegular,
    fontSize: RFPercentage(1.8),
    color: Colors.lightTheme.textSecondary,
  },
  divider: {
    height: 1,
    backgroundColor: '#EAEAEA',
    marginVertical: hp(1),
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: hp(0.3),
  },
  label: {
    fontFamily: Fonts.PoppinsMedium,
    color: Colors.lightTheme.textSecondary,
    fontSize: RFPercentage(1.8),
  },
  value: {
    fontFamily: Fonts.PoppinsRegular,
    color: Colors.lightTheme.textPrimary,
    fontSize: RFPercentage(1.8),
    maxWidth: wp(55),
    textAlign: 'right',
  },
  actionRow: {
    marginTop: hp(1.5),
    alignItems: 'center',
    alignSelf: 'flex-end',
    backgroundColor: Colors.lightTheme.primaryBtn?.BtnColor,
    paddingVertical: hp(1.2),
    borderRadius: 10,
    paddingHorizontal: wp(4),
  },
  actionText: {
    fontFamily: Fonts.PoppinsMedium,
    color: Colors.lightTheme.primaryBtn?.TextColor,
    fontSize: RFPercentage(1.8),
  },
});
